version: "3"
services:
  db:
    image: postgres:13.3
    environment:
      POSTGRES_USER: sample
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql
  # app:
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   command: npm run start
volumes:
  postgres:
