import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import "@mantine/core/styles.css"
import "@mantine/notifications/styles.css"

import {
  MantineProvider,
  ColorSchemeScript,
  MantineColorsTuple,
  createTheme,
} from "@mantine/core"
import { ClerkProvider } from "@clerk/nextjs"
import { Notifications } from "@mantine/notifications"

import QueryProvider from "./QueryProvider"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const myColor: MantineColorsTuple = [
  "#fbebff",
  "#efd3fc",
  "#dca5f5",
  "#c874ef",
  "#b74ae9",
  "#ac31e6",
  "#a822e6",
  "#9316cd",
  "#8311b8",
  "#7206a1",
]

const theme = createTheme({
  colors: {
    myColor,
  },
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="jp">
        <head>
          <ColorSchemeScript />
        </head>
        <body className={inter.className}>
          <QueryProvider>
            <MantineProvider forceColorScheme="dark" theme={theme}>
              {children}
              <Notifications />
            </MantineProvider>
          </QueryProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
