import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import '@mantine/core/styles.css';

import { MantineProvider, ColorSchemeScript, ColorSchemeScriptProps } from '@mantine/core';
import { ClerkProvider } from '@clerk/nextjs';
import { useState } from 'react';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <head><ColorSchemeScript /></head>
        <body ><MantineProvider
        forceColorScheme='dark'
        
        >{children}</MantineProvider></body>
      </html>
    </ClerkProvider>
  )
}

//className={inter.className}